# -*- coding: utf-8 -*-
"""RandomData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZJFJWwLLr2j14ABZ89Itl7_mfezSxXN
"""

import numpy as np
import string
import json
import time
import uuid
import random
import datetime
import sys
import ssl

coclave_id = str(uuid.uuid4()),
chars=string.ascii_uppercase + string.digits
ID = "1CSGCP2GE31EM126762Gabriella"
def upc():
    message = {
    "name": "PRODUCTO",
    "coclave_id":coclave_id,
    "COCLAVECIC": random.randint(0,121),
    "CODPRODUCTO":''.join(random.choice(chars) for _ in range(6)),
    "MARGEN_ACTIVO_SOL": random.uniform(0.1, 99.99),    
    "ID": ID,
    "CODMES": str(datetime.datetime.now())
    }
    print ("Message Published" + str(message))

while True:
    upc()